# ===================================================================
# Spring Boot configuration for the "dev" profile.
#
# This configuration overrides the application.yml file.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

spring:
    profiles:
        active: dev
    devtools:
        restart:
            enabled: true
        livereload:
            enabled: false # we use Grunt + BrowserSync for livereload
    data:
        mongodb:
            host: localhost
            port: 27017
            database: blogaggr
            
    mail:
        host: smtp.gmail.com
        port: 587
        username: emailid@gmail.com
        password: password
        protocol: smtp
        tls: true
        properties.mail.smtp:
            auth: true
            starttls.enable: true
            ssl.trust: smtp.gmail.com

#    mail:
#        host: smtp-mail.outlook.com
#        port: 587
#        username: emailid@outlook.com
#        password: ******
#        protocol: smtp
#        tls: true
#        properties.mail.smtp:
#            auth: true
#            starttls.enable: true
#            ssl.trust: smtp-mail.outlook.com

#    mail:
#        host: smtp.mail.yahoo.com
#        port: 587
#        username: emailid@yahoo.com
#        password: *******
#        protocol: smtp
#        tls: true
#        properties.mail.smtp:
#            auth: true
#            starttls.enable: true
#            ssl.trust: smtp.mail.yahoo.com

    messages:
        cache-seconds: 1
    thymeleaf:
        cache: false
    
    social:
        # see https://developers.google.com/+/web/signin/server-side-flow#step_1_create_a_client_id_and_client_secret
        google:
            clientId: googleclientid
            clientSecret:  googleclientsecret

        # see https://developers.facebook.com/docs/facebook-login/v2.2
        facebook:
            clientId: facebookclientid
            clientSecret: facebookclientsecret

        # see https://apps.twitter.com/app/
        twitter:
            clientId: twitterclientid
            clientSecret: twitterclientsecret

liquibase:
    contexts: dev

server:
    port: 8080

# ===================================================================
# JHipster specific properties
# ===================================================================

jhipster:       
    mail: # specific JHipster mail property, for standard properties see MailProperties
        from: blahblah@yahoo.com
      
    metrics: # DropWizard Metrics configuration, used by MetricsConfiguration
        jmx.enabled: true
        spark:
            enabled: false
            host: localhost
            port: 9999
        graphite:
            enabled: false
            host: localhost
            port: 2003
            prefix: blogaggr